# Pamplona 2019 
#  Playbook which checks is a patch is applicabe to a orale home 
#   

---
- name: patch full file 
  set_fact:
     patch_file: "{{media_dir}}/PSU/{{version}}/{{type}}/{{item.file}}"
  with_items: "{{PSU}}"
  when:  item.version == "{{version}}"  and  item.type == "{{type}}" and item.patch=="{{patch}}"

- name: look for the patch 
  stat:
    path: "{{patch_file}}"
  register: exsists 

- fail:
    msg: "ERROR: Source patch  {{patch_file}}  file not found"
  when: exsists.stat.readable ==  False
   
- name : unzip the patch
  unarchive:
    src: "{{patch_file}}"
    remote_src: yes
    dest: "{{stage_directory}}"

- name: Check opatch version  
  shell: "{{oracle_home}}/Opatch/opatch rereq CheckMinimumOPatchVersion  -phBaseDir {{stage_directory}}/{{patch}}"
  args:
    chdir: "{{ oracle_home }}"
  environment:
    CV_ASSUME_DISTID: OEL7.6
    ORACLE_HOME: "{{ oracle_home }}"
    PATH: "$PATH:{{ oracle_home }}/bin"
    LIBPATH: "$LIBPATH:{{ oracle_home }}/lib:{{ oracle_home }}/ctx/lib"
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ oracle_home }}/lib"
  register: opatch_output
  tags: opatch_version

- name: check opatch conflics
  shell: "{{oracle_home}}/Opatch/opatch prereq CheckConflictAgainstOHWithDetail -ph {{stage_directory}}/{{patch}}"
  args:
    chdir: "{{ oracle_home }}"
  environment:
    CV_ASSUME_DISTID: OEL7.6
    ORACLE_HOME: "{{ oracle_home }}"
    PATH: "$PATH:{{ oracle_home }}/bin"
    LIBPATH: "$LIBPATH:{{ oracle_home }}/lib:{{ oracle_home }}/ctx/lib"
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:{{ oracle_home }}/lib"
  register: opatch_output
  tags: opatch_conflicts
