#  Pamplona 2020
#  Playbook which sends a respone file and  uses it to install  Oracle restart/ CRS  / Grid on alone server
#  requires
#   env:                                     name of the server  which should be in the inventory
#   type:                                 asm or dba
#   version:                              version of database or asm
#   vars/oracle_standard.yaml           standard values for Oracle
#   vars/asm_binaries.xml:          Info with the asm binaries 
---
- hosts: "{{ env }}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
 # checking prerrequisites     
  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined or version is not defined or type is not defined
# Loading env
  - name: Including Standard_values
    include_vars:
      file: "vars/oracle_standard.yaml"

  - name: Including binaries info
    include_vars:
     file: "vars/{{type}}_binaries.yaml"
  - set_fact:
     oracle_home: "{{oracle_home_directory.asm}}"
    when: type == 'asm'
#
  - name: generate response file
    template:
     src: "templates/{{ version.response_file }}.j2"
     dest: "{{ stage_directory }}/{{ version.response_file}}"
     mode: '0644'
     tags: asm_template  


  - name: Install Grid  19c Software
  shell: "{{ oracle_home }}/gridSetup.sh  -silent -waitforcompletion -ignorePrereq  -responseFile {{ stage_directory }}/{{version.response_file}}"
    become: yes
    become_user: "{{ oracle_user }}"
    tags: gridsetup  
    args:
     chdir: "{{ oracle_home }}"
    environment:
      GI_HOME: "{{ oracle_home }}"
      ORACLE_HOME: "{{ oracle_home }}"
    ignore_errors: yes

  - name: execute root.sh
    shell: "{{ oracle_home }}/root.sh"
    become: yes
    become_user: root
    tags: rootsh
    args:
     chdir: "{{ oracle_home }}"

  - name: Configure CRS 
    shell: $GI_HOME/perl/bin/perl -I $GI_HOME/perl/lib -I $GI_HOME/crs/install $GI_HOME/crs/install/roothas.pl
    become: yes
    become_user: root
    args:
     chdir: "{{ oracle_home }}"
    environment:
      GI_HOME: "{{ oracle_home }}"
      ORACLE_HOME: "{{ oracle_home }}"
    ignore_errors: yes

  - name: Create listener
    shell: "$GI_HOME/bin/srvctl add listener -listener LISTENER  -oraclehome  {{ oracle_home }}" 
    become: yes
    become_user: "{{oracle_user}}"
    tags: create_listener  
    args:
     chdir: "{{ oracle_home }}"
    environment:
      GI_HOME: "{{ oracle_home }}"
      ORACLE_BASE: "{{ oracle_base}}"
    ignore_errors: no

  - name: Enable listener
    shell: $GI_HOME/bin/srvctl enable listener -listener LISTENER 
    become: yes
    become_user: "{{oracle_user}}"
    args:
     chdir: "{{ oracle_home }}"
    environment:
      GI_HOME: "{{ oracle_home }}"
      ORACLE_BASE: "{{ oracle_base}}"
    ignore_errors: yes

  - name: Start listener
    shell: $GI_HOME/bin/srvctl start listener -listener LISTENER 
    become: yes
    become_user: "{{oracle_user}}"
    args:
     chdir: "{{ oracle_home }}"
    environment:
      GI_HOME: "{{ oracle_home }}"
      ORACLE_BASE: "{{ oracle_base}}"
    ignore_errors: no

