#  Pamplona 2020
#  Playbook which creates a database
#
# requires
#   env:                                     name of the server  which should be in the inventory
#   vars/oracle_standard.yaml                 standard values for Oracle
---
- hosts: "{{env}}"
  remote_user: ansible
  tasks:

 # checking prerrequisites     
   - fail: 
       msg: "Error no server definied, please define the env variable in the job"
     when: env is not defined 

# Loading env
   - name: Including Standard_values
     include_vars:
      file: "vars/oracle_standard.yaml"

   - name: checking oratab
     shell:
       cmd: "cat /etc/oratab|grep +ASM |sed -e 's/# line added by Agent/ /g' -e 's/:/ /g'|awk '{ print $1}' "
     register: count

   - fail: 
       msg: "ERROR: The chain {{item}} exsists at  {{env}}  /etc/oratab file "
     when: item ==  "+ASM"
     with_items: 
      - "{{count.stdout_lines}}"

   - set_fact:
      oracle_home: "{{oracle_home_directory.asm}}"
     when: type == 'asm'


   - name: create ASM
     become: yes
     become_user: "{{oracle_user}}"
     shell:
       cmd: "{{ oracle_home }}/bin/asmca  -silent 
         -configureASM 
         -sysAsmPassword {{sysasm_passd}} 
         -asmsnmpPassword {{asmdbsnmp_passwd}} 
         -diskString \"/dev/oracleasm/disks/*\" 
         -diskGroupName {{oracle_hostname|upper}}_DATA 
         -disk \"/dev/oracleasm/disks/{{oracle_hostname|upper}}_DATA*\"  
         -redundancy EXTERNAL  "

   - name:  Create FRA
     become: yes
     become_user: "{{oracle_user}}"
     shell:
       cmd: "{{ oracle_home }}/bin/asmca  -silent
         -createDiskGroup
         -sysAsmPassword {{sysasm_passd}}
         -diskString \"/dev/oracleasm/disks/*\"
         -diskGroupName {{oracle_hostname|upper}}_FRA
         -disk \"/dev/oracleasm/disks/{{oracle_hostname|upper}}_FRA*\"
         -redundancy EXTERNAL  "


   - name: create REDO1
     become: yes
     become_user: "{{oracle_user}}"
     shell:
       cmd: "{{ oracle_home }}/bin/asmca  -silent
         createDiskGroup
         -sysAsmPassword {{sysasm_passd}}
         -diskString \"/dev/oracleasm/disks/*\"
         -diskGroupName {{oracle_hostname|upper}}_REDO1
         -disk \"/dev/oracleasm/disks/{{oracle_hostname|upper}}_REDO1*\"
         -redundancy EXTERNAL  "


   - name: create REDO2
     become: yes
     become_user: "{{oracle_user}}"
     shell:
       cmd: "{{ oracle_home }}/bin/asmca  -silent
         -createDiskGroup
         -sysAsmPassword {{sysasm_passd}}
         -diskString \"/dev/oracleasm/disks/*\"
         -diskGroupName {{oracle_hostname|upper}}_REDO2
         -disk \"/dev/oracleasm/disks/{{oracle_hostname|upper}}_REDO2*\"
         -redundancy EXTERNAL  "


