# Pamplona 2019 
#  Playbook which configures_asmlib
#  
#  requires
#    env:                             name of the server  which should be in the inventory
#    vars/oracle_standard.yaml        configuration file with all the deppartment values
---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
   - fail: msg="Error no server definied, please define the env variable in the job"
     when: env is not defined

   - name: "Including standard variables"
     include_vars:
       file: "vars/oracle_standard.yaml"
   - name:    configirando usuario 
     command: /usr/sbin/oracleasm configure -u "{{oracle_user}}"

   - name:     configurando grupo
     command:  /usr/sbin/oracleasm configure -g  "{{oracle_group}}"

   - name:     seteamos al arranque 
     command: /usr/sbin/oracleasm configure -e

   - name:    activamos el logical block 
     command:   /usr/sbin/oracleasm configure -b 

   - name:    arrancamos
     command:   /usr/sbin/oracleasm init


   - name:     comprobamos
     command:      /usr/sbin/oracleasm status
     register:     oasm_status
     changed_when: false
     failed_when:  false
     no_log:       true

   - name:         estado
     command:      /usr/sbin/oracleasm status
     register:     oasm_status
     changed_when: false
