#  Pamplona 2019
#  Playbook which sends a respone file and uses it ro install a database
#
# requires
#   env:                                     name of the server  which should be in the inventory
#     vars/oracle_standard.yaml   standard values for Oracle
---
- hosts: "{{env}}"
  vars:
    type: db
    action: binaries
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
 # checking prerrequisites     
   - fail: msg="Error no server definied, please define the env variable in the job"
       when: env is not defined
   - fail: msg="Error no server definied, please define the env variable in the job"
        when: version is not defined
# End prerrequisites  + check var file for improvement
#
# Loading env
   - name: Including Standard_values
     include_vars:
      file: "vars/oracle_standard.yaml"

  - set_fact:
     oracle_home: "{{oracle_home_directory.db}}"
    when: type == 'db'

#   
  - name: generate response file
    template:
     src: "templates/{{ response_file }}.j2"
     dest: "{{ stage_directory }}/{{response_file}}"
     mode: '0644'

## to improve, check if {{ oracle_home }}/runInstaller exsists
##
#
  - name: Install Oracle 19c Database Software
    shell: "{{ oracle_home }}/runInstaller -silent -responseFile {{ stage_directory }}/{{response_file}} -noconfig -ignorePrereqFailure"
    become: yes
    become_user: "{{ oracle_user }}"
    ignore_errors: True

  - name:  Executing orainstroot.sh
    shell: "{{ oracle_inventory }}/orainstRoot.sh"
    become: yes
    become_user: "{{ root_user }}"
    ignore_errors: True

 - name:  Executing root.sh
   shell: "{{ oracle_home }}/root.sh -silent"
   become: yes
   become_user: "{{ root_user }}"
   ignore_errors: True


