---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  
  - name: Including data
    include_vars:
      file: "{{type}}_install_{{ version }}.yaml"
   
  - name: Copy response file 
    copy:
     src: "files/{{ response_file }}"
     dest: "{{ stage_directory }}/{{response_file}}"
     owner: "{{ oracle_user }} "
     group: "{{ oracle_group }}"
    

  - name: Install Oracle 19c Database Software
    shell: "{{ oracle_home }}/runInstaller -silent -responseFile {{ stage_directory }}/{{response_file}} -noconfig -ignorePrereqFailure"
    become: yes
    become_user: "{{ oracle_user }}"
    ignore_errors: True

