# Pamplona 2019 
#  Playbook which installs crs, configure ASM disks and create asm instance
#  
#  requires
#   host: hostname to apply the kaybook which should be inventoried
#    env:                             name of the server  which should be in the inventory
#    req:                             number of request 
#    vars/main.yaml        configuration file with all the department values
#    vars/REQ.yaml           configuration file all the database required info

---
- hosts: "{{ env }}"
  vars:
    type: rdbms 
  vars_files:
    - "vars/main.yml"
    - "vars/{{req|upper}}.yml"
  remote_user: "{{ansible_user}}"
  
  pre_tasks:
  - name: fail if required variables are not defined
    fail:
     msg: "ERROR: Yo must define {{ item }} at this playbook"
    when: "{{ item }} is not defined"
    with_items:
      - env
      - req
      - version
      - sid 
  - name: Converting ORACLE_SID to uppercase
    set_fact:
     SID: "{{sid|upper}}"  
  roles:
     - { role:  db_check_sid, become: yes, become_user: "{{oracle_user}}" }
     - { role:  db_create_database, become: yes, become_user: "{{oracle_user}}" }

