# Pamplona 2019 
#  Playbook which installs crs, configure ASM disks and create asm instance
#  
#  requires
#   host: hostname to apply the kaybook which should be inventoried
#    env:                             name of the server  which should be in the inventory
#    req:                             number of request 
#    version:                         version of the database binaries 
#    vars/main.yaml        configuration file with all the deppartment values
#    vars/oracle_files.yaml           configuration file with all the  binarie locations

---
- hosts: "{{ env }}"
  vars:
    type: rdbms 
  vars_files:
    - "vars/main.yaml"
    - "vars/oracle_files.yaml"
  remote_user: "{{ansible_user}}"
  
  pre_tasks:
  - name: fail if required variables are not defined
    fail:
     msg: "ERROR: Yo must define {{ item }} at this playbook"
    when: "{{ item }} is not defined"
    with_items:
      - env
      - req
      - version
      - sid 

roles:
 - { role: db_create_database, become: yes, become_user: "{{oracle_user}}" }
