#  Pamplona 2019
#  Playbook which creates a database
#
# requires
#   env:                                     name of the server  which should be in the inventory
#   SID:                                     Oracle SID
#   version:                                 Version of the database
#   files/[type]_install_[version].yaml  : configuration file with the specific values for SID creation
#

---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:

  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined

  - fail: msg="Error no version definied, please define the version variable in the job"
    when: version is not defined

  - name: Including generic database type data 
    include_vars:
      file: "vars/{{type}}_install_{{ version }}.yaml"

  - name: specific  SID variables 
    include_vars:
      file: "files/{{type}}_createdb_{{ SID }}.yaml"

  - name: checking oratab
    shell: "cat /etc/oratab|grep {{SID}}|sed -e 's/# line added by Agent/ /g' -e 's/:/ /g'|wc -l "
    register: count
  
  - fail: 
      msg: "ERROR: The chain {{SID}} is  {{count.stdout}} times at {{env}}  /etc/oratab file "
    when: count.stdout != "0"

  - name: generate response file
    become: yes
    become_user: "{{ oracle_user}}"
    template:
     src: "templates/db_createdb_{{version}}.rsp.j2"
     dest: "{{ stage_directory }}/db_create_{{SID}}.rsp"
     mode: '0644'


  - name: createdb 
    become: yes
    become_user: "{{oracle_user}}"    
    shell: "{{ oracle_home }}/bin/dbca -silent -createDatabase  -ignorePreReqs -responseFile {{ stage_directory }}/db_create_{{SID}}.rsp"
    args:
      chdir: "{{ oracle_home }}"
    environment:
       CV_ASSUME_DISTID: OEL7.6


