# Pamplona 2019 
#  Playbook which executes the post installation scripts
#  
#  requires
#    env:                             name of the server  which should be in the inventory
#    files/packages_[version].yaml   configuration file with the paqueges required for this version of the database
---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined

  - name: Including data
    include_vars:
      file: "{{type}}_install_{{ version }}.yaml"

  - name:  Executing orainstroot.sh
    shell: "{{ oracle_inventory }}/orainstRoot.sh"
    become: yes
    become_user: "{{ root_user }}"
    ignore_errors: True

  - name:  Executing root.sh
    shell: "{{ oracle_home }}/root.sh -silent"
    become: yes
    become_user: "{{ root_user }}"
    ignore_errors: True

  - name: clean stage directory
    file: 
     path: "{{ stage_directory }}"
     state: absent
    become: yes
    become_user: "{{ root_user }}"

