# Pamplona 2019 
#  Playbook which check the S.O compliance (directories)
#  
#  requires
#   host: hostname to apply the kaybook which should be inventoried
#    env:                             name of the server  which should be in the inventory
#    vars/oracle_standard.yaml        configuration file with all the deppartment values
#    vars/oracle_files.yaml           configuration file with all the  binarie locations
---
- hosts: "{{ env }}"
  vars:
    type: asm 
  vars_files:
    - "vars/main.yml"
    - "vars/oracle_files.yml"
  remote_user: "{{ansible_user}}"
  
  pre_tasks:
  # Checking if we have the required variables
   - fail: 
        msg: | 
         ERROR:   please check variables:
             env:   name of the server  which should be in the inventory
             req:    number of request for the backout  
     when:  item  is not defined
     with_items:
      - env 
    
          
  roles:
    - role: check_sid
      vars:
        sid: +ASM
    - { role: oracle_directories , become: yes, become_user: "{{oracle_user}}" }
   
   
  
