# Pamplona 2019 
#  Playbook which create the required directories
#   
#   requires
#     env:                                  name of the server  which should be in the inventory
#     type:                                 type of installation [asm|db]    
#     version:                              version of database or asm
#     vars/oracle_standard.yaml   standard values for Oracle
#     ignore                                if it can ignore errors 
---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: oracle
  tasks:
# checking prerrequisites     
  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined
  - fail: msg="Error no server definied, please define the env variable in the job"
          when: env is not defined
# End prerrequisites  + check var file for improvement

# Loading env
  - name: Including Standard_values 
    include_vars:
      file: "oracle_standard.yaml"

  - name: adjusting oracle_home
    set_fact: "{{oracle_home}}" = "{{oracle_home_directory}}.{{type}}"
#
  - name: create  directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"
      mode: '0775'
    with_items:
      - "{{ root_directory }}"
      - "{{ stage_directory }}"
      - "{{ oracle_inventory }}"
      - "{{ oracle_base }}"
      - "{{ oracle_home }}"
    ignore_errors: "{{ ignore}}"
    tags:
      - create_directories


