# Pamplona 2019 
#  Playbook which create the required directories
#   
#   requires
#     env:                                  name of the server  which should be in the inventory
#     type:                                 type of installation [asm|db]    
#     files/[type]_install_[version].yaml   configuration file with the  variables requested for the installation
---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined

  - name: Including package
    include_vars:
      file: "{{type}}_install_{{ version }}.yaml"

  - name: create  directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"
      mode: '0775'
    with_items:
      - "{{ root_directory }}"
      - "{{ stage_directory }}"
      - "{{ oracle_inventory }}"
      - "{{ oracle_base }}"
      - "{{ oracle_home }}"
    ignore_errors: "{{ ignore}}"
    tags:
      - create_directories


