# Pamplona 2019 
#  Playbook which checks if teh hosts has all the requested prereequisites
#  
#  requires
#    env:                             name of the server  which should be in the inventory
#    vars/oracle_standard.yaml        configuration file with all the deppartment values
#    vars/so_[version]_requisites.yaml        configuration file with the packages required for this version of the software
---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined

  - name: "Including standard variables"
    include_vars:
     file: "vars/oracle_standard.yaml"

  - name: "Including So {{version}} requisites"
    include_vars:
     file: "vars/so_{{version}}_requisites.yaml"

  - name: Check  S.O 
    assert:
       that:
           - "ansible_os_family == ' RedHat'"
           - "ansible_distribution_version|inti =  7"
    tags: oscompatible

  - name: Check the oracle user 
    user:
      name: "{{oracle_user}}"
      uid:  "{{oracle_uid}}"  
      group: "{{oracle_group}}"
      shell: /bin/bash
    tags: orauser    

  - name: check required packages
    yum:
     name:  "{{package_name}}"
     state: latest
    tags: packages   


  - name : Kernel values 
    sysctl:
      name: "{{ item.name }}"
      value: "{{item.value}}"
      state: present  
      ignoreerrors: yes
      sysctl_file: /etc/sysctl.d/30-oracle.conf
    with_items: "{{kernel_values}}"
    tags: sysctl

  ##We execute Huge Pages separately
  - name: Huge Pages
    sysctl:
        name: vm.nr_hugepages
        value: "{{huge_pages}}"  
        state: present
        sysctl_file: /etc/sysctl.d/30-oracle.conf     
        ignoreerrors: yes  
    tags: huge_pages
  
  - name: Limits para el usuario 
    pam_limits:
      domain: oracle
      limit_type: soft
      limit_item: "{{ item.name }}"
      value: "{{item.value}}"
      ignoreerrors: yes
    with_items: "{{limits}}"
    tags: limits 
        
  - name: Disable firewall
    service: 
      name: firewalld 
      state: stopped 
      enabled: no
    tags: firewall

  - name:  disabling SElinux
    selinux:
     policy: targeted
     state: disabled
    tags: SELinux
