---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined

  - name: Including package
    include_vars:
     file: "packages_{{oracle_version}}.yaml"

  - name: check packages "{{package_name}}"
    yum:
      name: "{{package_name}}"
      state: present
    with_items:
      - "{{ package_name }}"
    ignore_errors: "{{ ignore}}"