# Pamplona 2019 
#  Playbook which checks if required packages ares installed at the destination server
#  
#  requires
#    env:                             name of the server  which should be in the inventory
#    type:                            type of installation [asm|db]   
#    vars/packages_[type]_[version].yaml   configuration file with the packages required for this version of the software
---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - fail: msg="Error no server definied, please define the env variable in the job"
    when: env is not defined

  - name: Including package
    include_vars:
     file: "packages_{{type}}_{{version}}.yaml"

  - name: check packages "{{version.package_name}}"
    yum:
      name: "{{package_name}}"
      state: latest
    with_items:
      - "{{ version.package_name }}"
