#  Pamplona 2019
#   test playbook for short commands
#
# requires
#   env:                                     name of the server  which should be in the inventory

---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:

  - fail: 
     msg: "ERROR: SOME VARIABLE NOT DEFINED: Please define   env , version and SID variables "
    when: env is not defined  

  - name: Including generic database type data 
    include_vars:
     file: "vars/oracle_standard.yaml"
  - name: Including binaries info
    include_vars:
     file: "vars/{{type}}_binaries.yaml"
 
  - debug:        
      msg: "version es  {{version|regex_replace('r','.')|regex_replace('v','')}}"  

...
#  - debug:
#      msg: "El valor que buscamos es  {binaries.version.binary_name}} "
