#  Pamplona 2019
#   test playbook for short commands
#
# requires
#   env:                                     name of the server  which should be in the inventory
#   SID:                                     Oracle SID
#   version:                                 Version of the database
#   files/[type]_install_[version].yaml  : configuration file with the specific values for SID creation
#

---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:

  - fail: 
     msg: "ERROR: SOME VARIABLE NOT DEFINED: Please define   env , version and SID variables "
    when: env is not defined or version is not defined or SID is not defined 

  - name: Including generic database type data 
    include_vars:
      file: "oracle_standard.yml"

  - name: Checking if exsists FS directories before create database 
    stat:
     path: "{{ item }}"
    register: file_details
    with_items:
      - "/oradata/{{ SID }}/data"
      - "/oradata/{{ SID }}/fra"
      - "/oradata/{{ SID }}/temp"
      - "/oradata/{{ SID }}/redo"
  - fail: 
      msg: "ERROR: Directory {{item.item}}  do not exsists"
    when: "item.stat.exists != True"
    with_items: "{{ file_details.results }}"
  

 
  #- fail: 
  #    msg: "ERROR: Directory {{item.item}} , tenemos que exsists {{item.stat.exsist}}do not exsists"
  #  when:  item.stat.exsists is false
  #  with_items: "{{ file_details.results }}"


