# Pamplona 2020
#  Playbook which unzips the requeted file 
#    
#     requires
#       env:                                  name of the server  which should be in the inventory
#       type:                                 type of installation [asm|db]    
#      version:                              version of database or asm
#      vars/oracle_standard.yaml   standard values for Oracle
#      vars/oracle_binaries.yaml   file information
#
---
- hosts: "{{env}}"
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
# checking prerrequisites     
  - fail: msg="Error no server definied, please define the env and type variable in the job"
    when: env is not defined or type is not defined or version is not defined
# Loading env
  - name: Including Standard_values 
    include_vars:
     file: "vars/oracle_standard.yaml"

  - name: Including binaries info
    include_vars:
      file: "vars/oracle_files.yaml"

# retrieve the zip file 
  - set_fact:
      binary_file: "{{item.file}}"
    with_items: "{{binaries}}"
    when:  item.version ==  "19.3"  and  item.type == "asm"  
  
  - name: check for required binaries
    stat:
     path: "{{media_dir}}/{{binary_file}}"
    register: exsists
  - debug:
      msg: The file is availabe 
    when: exsists.stat.readable == True

  - fail:
      msg: "ERROR: Source zip file not found"
    when: exsists.stat.readable ==  False
    ignore_errors: False 

  - set_fact:
     oracle_home: "{{oracle_home_directory.db}}"
    when: type == 'db'

  - set_fact:
     oracle_home: "{{oracle_home_directory.asm}}"
    when: type == 'asm'

  - debug:
     msg: " File exsists. unzipping {{media_dir}}/{{binary_file}}  {{ oracle_home }}

  - name: Extract "{{media_dir}}/{{binary_file}}  {{ oracle_home }}"
    unarchive:
      src: "{{media_dir}}/{{binary_file}}"
      remote_src: yes
      dest: "{{ oracle_home }}"
    tag: unzipping
    become: yes
    become_user: "{{ oracle_user}}"

