# Pamplona 2019 
#  Playbook which checks if the SID exsists at server ENV
#   This is a control playbook, if the result is not true it will exsist with FAIL
#  requires
#    env:                             name of the server  which should be in the inventory
#    SID:                               oracle SID defined at /etc/oratab
---
  - name: checking oratab
    shell: "cat /etc/oratab|grep {{SID}}|sed -e 's/# line added by Agent/ /g' -e 's/:/ /g'|awk '{ print $1}' "
    register: count
  
  - fail: 
      msg: "ERROR: The chain {{item}} exsists at {{env}}  /etc/oratab file "
    when: item ==  "{{SID}}"
    with_items: 
     - "{{count.stdout_lines}}"



