#" Pamplona 2020
#  Playbook which unzips the requeted file 
#    
#     requires
#       env:                                  name of the server  which should be in the inventory
#       type:                                 type of installation [asm|rdbms]    
#      version:                              version of database or asm
#      vars/main.yaml                         standard values for Oracle
#      vars/oracle_binaries.yaml              file information
#
---
  - name: constructing the zip file name and path 
    set_fact:
      binary_file: "{{version}}/{{type}}/{{item.file}}"
    with_items: "{{binaries}}"
    when:  item.version == "{{version}}"  and  item.type == "{{type}}"  
  
  - name: check for required binaries
    stat:
     path: "{{media_dir}}/{{binary_file}}"
    register: exsists
  - debug:
      msg: "OK: Binary file {{media_dir}}/{{binary_file}} exsists, we continue " 
    when: exsists.stat.readable == True

  - fail:
      msg: "ERROR: Source zip file not found"
    when: exsists.stat.readable ==  False
    ignore_errors: False 

  - name: gathering oracle home variable if the type is database 
    set_fact:
     oracle_home: "{{oracle_home_directory.rdbms}}"
    when: type == 'rdbms'

  - name: gathering oracle home variable if the type is grid
    set_fact:
     oracle_home: "{{oracle_home_directory.asm}}"
    when: type == 'asm'

  - debug:
     msg: " File exsists. unzipping {{media_dir}}/{{binary_file}}  {{ oracle_home }}"

  - name:  "Extract {{media_dir}}/{{binary_file}}  {{ oracle_home }}"
    unarchive:
      src: "{{media_dir}}/{{binary_file}}"
      remote_src: yes
      dest: "{{ oracle_home }}"
    
    

