#" Pamplona 2020
#  Playbook which unzips the requeted file 
#    
#     requires
#       env:                                  name of the server  which should be in the inventory
#       type:                                 type of installation [asm|rdbms]    
#      version:                              version of database or asm
#      unzip_dest                             destination of unzipped files 
#      vars/main.yml                         standard values for Oracle
#      vars/oracle_files.yml                 file information
#
---
  - name: constructing the zip file name and path 
    set_fact:
      binary_file: "{{version}}/{{type}}/{{item.file}}"
    with_items: "{{binaries}}"
    when:  item.version == "{{version}}"  and  item.type == "{{type}}"  
  
  - name: check for required binaries
    stat:
     path: "{{media_dir}}/{{binary_file}}"
    register: exsists
  - debug:
      msg: "OK: Binary file {{media_dir}}/{{binary_file}} exsists, we continue " 
    when: exsists.stat.readable == True

  - fail:
      msg: "ERROR: Source zip file not found"
    when: exsists.stat.readable ==  False
    ignore_errors: False 

  - debug:
     msg: " File exsists. unzipping {{media_dir}}/{{binary_file}}  {{ unzip_dest }}"

  - name:  "Extract {{media_dir}}/{{binary_file}}  {{ unzip_dest }}"
    unarchive:
      src: "{{media_dir}}/{{binary_file}}"
      remote_src: yes
      dest: "{{ unzip_dest }}"
    
    

