# Pamplona 2020
#  Playbook which creates a database
#
# requires
#   env:                                     name of the server  which should be in the inventory
#   SID:                                     Oracle SID
#   version:                                  Version of the database
#   req:                                     request number with the database creation information
#   vars/oracle_standard.yaml                 standard values for Oracle
#   files/REQ.yml         specific values dor this db creation
---
  - name: setting variables 
     set_fact:
         oracle_home: "{{oracle_home_directory.rdbms}}"
         datafileDestination: "{{ lookup('vars', 'data_location'.[storageType])}}"
   
  - debug: 
      msg: |
         storageType  is set to {{storageType}}
         ORACLE_HOME  is set to {{oracle_home}}

## to improve
## in case of FS check if its mount point and create the subfolders
#  - name: If we are in a FS installation we check if directories exsists
#    stat:
#      path: "{{ item }}"
#    register: file_details
#    with_items:
#      - "/oradata/{{ SID }}/data"
#      - "/oradata/{{ SID }}/fra"
#      - "/oradata/{{ SID }}/temp"
#      - "/oradata/{{ SID }}/redo"
#    when:'storageType=FS'
 

  - name: generate response file
    become: yes
    become_user: "{{ oracle_user}}"
    template:
     src: "templates/db_createdb_{{version}}.rsp.j2"
     dest: "{{ stage_directory }}/db_createdb_{{SID}}.rsp"
     mode: '0644'

  - name: createdb 
    become: yes
    become_user: "{{oracle_user}}"    
    shell: "{{ oracle_home }}/bin/dbca -silent -createDatabase  -ignorePreReqs -responseFile {{ stage_directory }}/db_createdb_{{SID}}.rsp"
    args:
      chdir: "{{ oracle_home }}"
    environment:
       CV_ASSUME_DISTID: OEL7.6


