# Pamplona 2019 
#  Playbook which create the required directories
#   
#   requires
#     env:                                  name of the server  which should be in the inventory
#     type:                                 type of installation [asm|rdbms]    
#     version:                              version of database or asm
#     vars/main.yaml                        standard values for Oracle
---
  - set_fact:  
     oracle_home: "{{oracle_home_directory.rdbms}}"
    when: type == "rdbms"

  - set_fact:
     oracle_home: "{{oracle_home_directory.asm}}"
    when: type == "asm"

#
  - name: create  directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"
      mode: '0775'
    with_items:
      - "{{ root_directory }}"
      - "{{ oracle_inventory }}"
      - "{{ oracle_base }}"
      - "{{ oracle_home }}"
      - "{{ oracle_scripts_dir }}"
      - "{{ oracle_scripts_dir }}/rman"
      - "{{ oracle_logs_dir }}"
      - "{{ stage_directory }}"
    ignore_errors: no
    tags:
      - create_directories
      
  - name: copy DBA team scripts 
    copy:
      src: "{{media_dir}}/scripts{{item.path}}{{item.file}}"
      dest: "{{oracle_scripts_dir}}{{item.path}}{{item.file}}"
      remote_src: yes
      owner: "{{ oracle_user }}"
      group: "{{ oracle_group }}"
      mode: '0775'
    with_items: "{{SCRIPTS}}"
    ignore_errors: no
    tags:
      - copy_scripts  

  - name: Adding envsel_new to profile
    lineinfile:
     dest: "{{oracle_user_home}}/.bash_profile"
     regexp: 'alias $ora_envsel_new.sh$'
     line: alias se='. {{oracle_scripts_dir}}/ora_envsel_new.sh'
     state: present
    tags: ora_envsel

  - name: Setp cron file 
    copy:
     dest: /var/spool/cron/oracle
     content: |
              # .---------------- minute (0 - 59)
              # |  .------------- hour (0 - 23)
              # |  |  .---------- day of month (1 - 31)
              # |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
              # |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
              # |  |  |  |  | 
              # *  *  *  *  * user-name  command to be executed
              PATH =$PATH:/bin:/usr/bin:/sbin:/usr/local/sbin:/usr/sbin:/usr/local/bin:$HOME/scripts
              MAILTO=admins_oracledba@company.org
              # Housekeeping
              01 00 * * *  "{{oracle_scripts_dir}}"/audit_trace_file_management.sh 31 &>/dev/null

     force: no
     owner: "{{oracle_user}}"
     group: "{{oracle_group}}"
     mode: 0600
    become: yes
    become_user: "{{ root_user}}"
    tags: crontab
    ignore_errors: yes      
 
